import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'


test('watch API config is generated from an operator-supplied origin without logging it', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'jarvis-watch-config-'))
  const output = join(directory, 'api-config.js')
  const origin = 'https://watch-api.example'
  try {
    const result = spawnSync(
      process.execPath,
      ['scripts/generate-watch-config.mjs', '--output', output],
      {
        cwd: process.cwd(),
        env: { ...process.env, JARVIS_WATCH_API_ORIGIN: origin },
        encoding: 'utf8',
      },
    )
    assert.equal(result.status, 0, result.stderr)
    assert.doesNotMatch(result.stdout + result.stderr, /watch-api\.example/)
    const generated = await readFile(output, 'utf8')
    assert.match(generated, /https:\/\/watch-api\.example/)
    assert.match(generated, /\/api\/v1/)
  } finally {
    await rm(directory, { recursive: true, force: true })
  }
})

test('watch API config has a safe deterministic default for clean-clone builds', async () => {
  const [example, localExample, rootIgnore, readme] = await Promise.all([
    readFile('watch/app-side/api-config.example.js', 'utf8'),
    readFile('watch/.env.local.example', 'utf8'),
    readFile('.gitignore', 'utf8'),
    readFile('README.md', 'utf8'),
  ])
  assert.match(example, /127\.0\.0\.1:8080/)
  assert.doesNotMatch(example, /192\.168\.|\.lan\b/)
  assert.equal(localExample, 'JARVIS_WATCH_API_ORIGIN=http://127.0.0.1:8080\n')
  assert.match(rootIgnore, /!watch\/\.env\.local\.example/)
  assert.match(readme, /watch\/\.env\.local\.example/)

  const directory = await mkdtemp(join(tmpdir(), 'jarvis-watch-default-'))
  const output = join(directory, 'api-config.js')
  try {
    const result = spawnSync(
      process.execPath,
      ['scripts/generate-watch-config.mjs', '--ignore-local-override', '--output', output],
      { cwd: process.cwd(), env: { ...process.env, JARVIS_WATCH_API_ORIGIN: '' }, encoding: 'utf8' },
    )
    assert.equal(result.status, 0, result.stderr)
    assert.doesNotMatch(result.stdout + result.stderr, /127\.0\.0\.1:8080/)
    assert.equal(await readFile(output, 'utf8'), example.replace(
      '// Safe clean-clone fallback. The generator copies this behavior when no local origin is set.',
      '// Generated by scripts/generate-watch-config.mjs; do not commit.',
    ))
  } finally {
    await rm(directory, { recursive: true, force: true })
  }
})
